name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: change directory
      run: cd Fourier_1d
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make conv
      run: make conv
